branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: todo-nest-env
global:
  application_name: todo-nest-to-aws-eb
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
